language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=PSR2 src/
  - phpunit

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
