language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer install --dev --no-interaction
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=PSR2 src/
  - phpunit

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
